### ISSUE TITLE
Problem With Degree sign and material font

### ISSUE THREAD

**Issue by Noob-linux-user** [closebox73/Taurus#3]
As You may already know, the Degree sign doesn't show in certain desktop environment like cinnamon and gnome. A Redditor said that it is due to the fact that the script text is not coded in utf-8 or something. Instead, it may use the old coded form. Maybe you can look after it. Also, the material font didn't work for some reason. 
And can you make the music widget to support Spotify. I may have found a similar conky which can show the music widget.

![Screenshot from 2022-08-22 19-50-17 resized](https://user-images.githubusercontent.com/107858045/185947513-590e3b18-6c49-4e25-88fc-c322ba1801a9.png)

**Comment by closebox73** [comment]
what **Font** do you use?  I think I took the degree symbol from the openwatermap website

**Comment by Noob-linux-user** [comment]
Your conky widgets are missing this line
override_utf8_locale = true
otherwise, some character doesn't show properly in certain desktop

**Comment by closebox73** [comment]
what??  looks like i have to update all my theme config, thanks a lot..😂

**Comment by Noob-linux-user** [comment]
haha yes, that will be a lot of work
