### ISSUE TITLE
Api errors for open weather

### ISSUE THREAD

**Issue by ValkyriaGH** [closebox73/Taurus#7]
It seems that Openweather has changed policy regarding API. Now the json throws invalid API error. Now it seems that it's not free over 1000 calls per day, I don't now it before was free.
I guess you can create an account and use your own API key. In the config files:

> {font Roboto Condensed:size=12}Today the weather in ${execi **120** cat ~/.cache/weather.json | jq -r '.name'} is ${execi **120** cat ~/.cache/weather.json | jq -r '.weather[0].description' | sed "s|\<.|\U&|g"}${font}

The bolded part I'm guessing is the seconds between calls to the weather.sh and therefore to the API right? Sorry I'm not really a programmer.

**Comment by closebox73** [comment]
@ValkyriaGH I've given advice to make an api key separately, and I think that many of those using my theme use the default api key, resulting in overuse.

**Comment by closebox73** [comment]
@ValkyriaGH interval between calling API is 
> ${execi **200** ~/.config/conky/themename/scripts/weather-v2.0.sh

**Comment by ValkyriaGH** [comment]
@closebox73  Thank you for your quick replay. I guess that if I change the line to 6000 I will call the API every 10 minutes so never should I ever exceed the limit for 1000 calls a day.

**Comment by closebox73** [comment]
@ValkyriaGH You are right, I should update themes that use weather info.
Thanks
